# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcef93d432d261de6375c7643bf41f0b7fb136455d1d8f2dc0af05d8c5d48a2c340a114543627b32fbeb8c5516e4738bd12298378640a5049d083220796c6b5b

test:
  secret_key_base: 6868d2ebcb25415e542f6f21e67e4a038119835b85c3ad4ef26658400a20f87e0619381a623f13b67846f5b7f360601ced351a22dbe425070ac8beae1a066e99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
